Refactor authentification
microservices-course-itmo/user-service pull request #21
Opened 2020-10-15 19:22 UTC by ArtemDavletov

Refactor authentification

2020-10-15 19:29 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
>          }
кажется, этот catch очень много ненужного захватывает

2020-10-15 19:33 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            throw new JwtException("JWT token is expired or invalid");
мне кажется лучше вернуть наш exception, позже надо будет exception handler делать, будет удобнее с собственными работать

2020-10-15 19:35 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
>          return repository.findByPhoneNumber(phoneNumber);
мы обычно конвертим entity сразу в dto и работаем с ними: modelMapper.map(repo.findBy...(), getDtoClass())

2020-10-15 19:36 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
> +    }
лучше вынести в отдельный класс, назвать что-то типа UserDtoToUserResponseMapper (чем больше букв в названии класс, тем солиднее код :) )
можно сделать бином и инжектить, можно сделать статичный метод и просто юзать

2020-10-15 19:40 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        }
давай в этом catch ловить JwtAuth...Exception какой-нибудь, который точно значит, что аутентификация не удалась и кидать unauthorized, а какие-то другие эксепшены позже будет хендлер ловить и кидать 500 ошибку на них.

2020-10-15 19:40 UTC, Kot1que requested changes
в целом круто, по мелочи поправить надо

2020-10-17 18:03 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
>      }
не используется, насколько я вижу

2020-10-17 21:03 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
>          }
Done

2020-10-17 21:04 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            throw new JwtException("JWT token is expired or invalid");
Вернул обратно `JwtAuthenticationException`

2020-10-17 21:04 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
>          return repository.findByPhoneNumber(phoneNumber);
Сделал, чтобы возвращался `UserDto`

2020-10-17 21:04 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
> +    }
Done

2020-10-17 21:06 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        }
Теперь ловит `JwtAuthenticationException` из `JwtTokenProvider`

https://github.com/microservices-course-itmo/user-service/pull/21#discussion_r505790083

2020-10-17 21:06 UTC, Kot1que approved these changes

2020-10-17 21:06 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
>      }
Убрал регистрацию

2020-10-17 21:06 UTC, merged