Add endpoint /refresh
microservices-course-itmo/user-service pull request #23
Opened 2020-10-18 14:34 UTC by ArtemDavletov

Add endpoint /refresh

2020-10-18 15:02 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            claims.setSubject("REFRESH_TOKEN");
сеттер меняет одно и то же поле разными значениями

2020-10-18 15:03 UTC, Kot1que requested changes
токен некорректный возвращается

2020-10-19 08:21 UTC, ArtemDavletov commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            claims.setSubject("REFRESH_TOKEN");
Поправил

2020-10-19 08:22 UTC, ArtemDavletov commented
![image](https://user-images.githubusercontent.com/19683603/96419826-57100d80-11fd-11eb-817d-b110b604a93f.png)

Поправлено: https://github.com/microservices-course-itmo/user-service/pull/23#pullrequestreview-511153210

2020-10-19 09:44 UTC, ArtemDavletov commented
1) Добавил проверку типа токена в endpoint `/refresh`;
2) поправил `getPhoneNumber`;
3) добавил `getTokenType` в `JwtTokenProvider`

2020-10-19 09:47 UTC, Kot1que approved these changes

2020-10-19 09:47 UTC, merged