Спринт 3
microservices-course-itmo/user-service pull request #26
Opened 2020-10-19 10:28 UTC by Kot1que

Аутентификация с помощью файрбейс
Регистрация с помощью файрбейс
Валидация токенов
Рефреш токенов

2020-10-21 11:15 UTC, andrsuh commented on pom.xml
> +            <version>0.9.1</version>
версии в проперти)

2020-10-21 11:17 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/configuration/FirebaseConfiguration.java
> +            log.debug("Firebase config is missing");
это не debug, а самый настоящий FATAL. Причем для него бы сделать NotableEvent отдельный и логать EventLogger-ом

2020-10-21 11:18 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +            e.printStackTrace();
никогда та не делайте)

2020-10-21 11:19 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        if(user == null){
форматирование

2020-10-21 11:19 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/configuration/FirebaseConfiguration.java
> +            log.debug("Firebase config is missing");
Ну, на самом деле от отсутствия этого конфига упадет только аутентификация и регистрация, весь остальной сервис продолжит работать. Но в целом да, согласен, severity поднимем и ивент сделаем.

2020-10-21 11:22 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        if(user == null){
Не понял, что ты имеешь ввиду. Уточни, пожалуйста

2020-10-21 11:22 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +            e.printStackTrace();
имеет ли смысл дальше идти?  NotableEvent точно

2020-10-21 11:23 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        AuthenticationResponse authenticationResponse = new AuthenticationResponse();
сделайте сеттер ломбоковский

2020-10-21 14:43 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    public ResponseEntity<ListWineUserDto> findUserTokensByWine(@PathVariable Long id) {
название метода

2020-10-21 14:44 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    public final ListSubscriptionService listSubscriptionService;
почему list?

2020-10-21 14:44 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/ListSubscriptionDto.java
>  public class ListSubscriptionDto implements AbstractDto<Long> {
название не нравится

2020-10-21 14:45 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/ListWineUserDto.java
> +    private List<UserTokens> users;
почему UserTokens == user?

2020-10-21 14:46 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/UserTokens.java
> +public class UserTokens {
что это и зачем?

2020-10-21 14:47 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/response/UserResponse.java
> +    private String number;
что такое number?

2020-10-21 14:47 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/response/mapper/UserDtoToUserResponseMapper.java
> +    public static UserResponse getUserResponse(UserDto user) {
у нас есть уже готовые ModelMapper, используйте

2020-10-21 14:49 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/repository/ListSubscriptionRepository.java
> +public interface ListSubscriptionRepository extends CrudRepository<ListSubscription, Long> {
название странное. Может просто SubscriptionRepository?

2020-10-21 14:50 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +        secret = Base64.getEncoder().encodeToString(secret.getBytes());
переприсваивание заинжекченного поля. Лучше сделай еще одно

2020-10-21 14:51 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +        Date now = new Date();
Не принято работать с типом Date. Лучше использовать long для хранения миллисекунд и через  long  производить все операции

2020-10-21 14:52 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            return false;
логируем и лови уже просто Exception

2020-10-21 14:53 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/ListSubscriptionService.java
> +    public ListWineUserDto getUserTokens(Long id) {
автоформатирование

2020-10-21 14:54 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/ListSubscriptionService.java
> +        List<ListSubscriptionDto> listSubscription = this.findUsersByItemId(id);
что за Item? Если это id вина, то, может, просто wine?

2020-10-21 14:55 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
> +            return null;
выглядит не оч

2020-10-21 14:58 UTC, andrsuh commented on src/main/resources/application.properties
> +firebase.url=https://testfire-1bc2f.firebaseio.com
добавим в env?

2020-10-21 14:58 UTC, andrsuh commented on src/main/resources/application.properties
> +user.role.user.id=1
?

2020-10-21 14:59 UTC, andrsuh commented on src/main/resources/application.properties
> +jwt.token.secret=jwtsecret
env?

2020-10-21 15:00 UTC, andrsuh reviewed
пара комментов

2020-10-21 15:01 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/configuration/FirebaseConfiguration.java
> +            log.debug("Firebase config is missing");
да, но FATAL, чтобы алерт в будущем прилетел. Потому то все-таки это важная функция

2020-10-21 15:01 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        if(user == null){
сделайте автоформатирование всех файлов перед коммитом. Можно галочку поставить, когда коммитите через идею

2020-10-21 15:02 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +        if(user == null){
отступы плохие

2020-10-25 13:31 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    public ResponseEntity<ListWineUserDto> findUserTokensByWine(@PathVariable Long id) {
Уже в рамках задачи следующего спринта все порефакторили, тут менять не буду, чтоб не было конфликтов.

2020-10-25 13:32 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    public final ListSubscriptionService listSubscriptionService;
Аналогично, поменяли всё в следующем спринте.

2020-10-25 13:32 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/dto/ListSubscriptionDto.java
>  public class ListSubscriptionDto implements AbstractDto<Long> {
Аналогично, названия и прочее в следующем спринте все отрефакторили.

2020-10-25 13:32 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/dto/ListWineUserDto.java
> +    private List<UserTokens> users;
Аналогично, названия и прочее в следующем спринте все отрефакторили.

2020-10-25 13:33 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/entity/UserTokens.java
> +public class UserTokens {
Нам надо отдавать список токенов для нотификейшнов (андроид, айос) для сервиса нотификаций. Название изменим на более говорящее.

2020-10-25 13:33 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/response/UserResponse.java
> +    private String number;
Аналогично, названия и прочее в следующем спринте все отрефакторили.

2020-10-25 13:34 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/repository/ListSubscriptionRepository.java
> +public interface ListSubscriptionRepository extends CrudRepository<ListSubscription, Long> {
Аналогично, названия и прочее в следующем спринте все отрефакторили.

2020-10-25 13:35 UTC, Kot1que commented on src/main/resources/application.properties
> +user.role.user.id=1
Айди для дефолтных двух ролей, который инсёртятся в бд миграцией. Если есть какое-то более красивое решение, то поменяем

2020-10-25 13:38 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/AuthenticationController.java
> +            e.printStackTrace();
Не совсем понимаю зачем нам логгировать неудачную аутентификацию пользователя. Вполне обычный сценарий, когда приходит какой-то кривой токен (например, от злоумышленника :) ). Можешь пояснить?

2020-10-25 13:55 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/ListSubscriptionService.java
> +        List<ListSubscriptionDto> listSubscription = this.findUsersByItemId(id);
Аналогично, названия и прочее в следующем спринте все отрефакторили.

2020-10-25 13:56 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            return false;
Аналогично, не очень понятно зачем логгировать невалидный токен. Поясни, пожалуйста.

2020-10-25 20:57 UTC, shinehlina requested changes
Ну короче очень мало. Напишите в личку, как исправите, я быстро апрув поставлю

2020-10-25 20:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/user/service/security/JwtTokenProvider.java
> +            return false;
Надо все-таки залогировать. Хотя бы на дебаг, потом может понадобится узнать

2020-10-25 20:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/user/service/service/UserService.java
> +        userDto.setRole(roleService.getById(ROLE_USER_ID));
Зачем вам это в проперти, если вы по факту всегда хотите роль "User"? Так что уберитк оттуда, как Андрей писал)

2020-10-26 15:31 UTC, shinehlina approved these changes

2020-10-26 15:32 UTC, merged