Sprint01
microservices-course-itmo/user-service pull request #5
Opened 2020-09-28 08:34 UTC by Kot1que

- Каркас приложения
- Первый вариант сущностей для пользователя, его роли, города и компании(для "бизнес"-аккаунтов, пока под вопросом)
- Базовая версия регистрации и get by id

2020-09-28 11:57 UTC, Anglopol requested changes

2020-09-28 11:57 UTC, Anglopol commented on pom.xml
> +        <protobuf-plugin.version>3.1.0.1</protobuf-plugin.version>
Вы уверены, что это необходимо?

2020-09-28 11:57 UTC, Anglopol commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@EqualsAndHashCode
Data уже включает в себя ToString и EqualsAndHashCode (исправьте во всех файлах)

2020-09-28 12:26 UTC, andrsuh requested changes
Супер! Небольшие замечания по стилю в основном :) Давайте не будем делать классы слишком детальными и близкими к реальным проектам, пока упростим. Так же не забывайте про джавадок

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +
что за пробелы?

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    @GetMapping("/get")
не нужно никаких глаголов get/register. Просто POST запрос на /users создает, GET по id - возвращает Читаем про модель зрелости Ричардсона

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/AbstractDto.java
> +public interface AbstractDto<I> {
какой смысл в данном интерфейсе?

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/AbstractDto.java
> +public interface AbstractDto<I> {
и почему в названии интерфейса Abstract  так-то он всегда такой :)

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/RoleDto.java
> +    private Boolean accessToCatalog;
оверхед, все нужно упрощать

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/dto/UserDto.java
> +    private RoleDto role;
логичнее было бы хранить массив ролей, а не сущность с кучей флажков имхо

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/AbstractEntity.java
> +public interface AbstractEntity<I> {
тот же вопрос

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@Data
не стоит вообще использовать автосгенерированные equals/hc по всем полям (включая изменяемые, например) Хибернейт вас за это накажет больно

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@Data
И вообще не используйте Data, только Getter/Setter по необходимости!

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@Table(name = "dim_city")
никаких `dim`

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +    @Column(name = "CityId")
колонки с маленькой буквы, префикс City тут вообьще не нужен, сокращаем

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/repository/AbstractRepository.java
> +public interface AbstractRepository<E extends AbstractEntity<I>, I> extends CrudRepository<E, I> {
Зачем?

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/repository/AbstractRepository.java
> +public interface AbstractRepository<E extends AbstractEntity<I>, I> extends CrudRepository<E, I> {
Спринг за вас уже сделал

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/CommonService.java
> +public interface CommonService<I, M extends AbstractDto<I>, E extends AbstractEntity<I>> {
Зачем? Зачем параметризованный? Параметры типа не задокументированы? Я не понимаю что за ними стоит

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +public abstract class AbstractService
зачем нам абстрактный сервис?

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +@Transactional
кто-нибудь сможет объяснить что это и как работает?

2020-09-28 12:26 UTC, andrsuh commented on src/main/java/com/wine/to/up/user/service/service/impl/RoleService.java
> +public class RoleService extends AbstractService<Long, RoleDto, Role, RoleRepository> {
Дофига непонятных классов

2020-09-28 12:26 UTC, andrsuh commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming.physical-strategy=com.wine.to.up.user.service.configuration.NamingStrategy
заяем?

2020-09-28 12:26 UTC, andrsuh commented on src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.postgresql.Driver
странно, я думал это есть, как оно иначе работало раньше?

2020-09-28 12:29 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/dto/RoleDto.java
> +    private Boolean accessToCatalog;
Как раз в адженде обсудить роли на сегодняшнем планнинге.

2020-09-28 12:32 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +public abstract class AbstractService
Чтобы круд операции с сущностями не писать в каждом сервисе снова, они все равно одинаковые

2020-09-28 13:04 UTC, shinehlina requested changes

2020-09-28 13:04 UTC, shinehlina commented on .gitignore
> +/**/application-dev.properties
Это зачем?

2020-09-28 13:04 UTC, shinehlina commented on pom.xml
> +
Апните версию

2020-09-28 13:04 UTC, shinehlina commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +    @Column(name = "CityId")
Если будет в бд snake, то не придется писать "@Column" над полями, все сделается магией

2020-09-28 13:08 UTC, Kot1que commented on .gitignore
> +/**/application-dev.properties
1. для использования настроек редактора локально для проекта, потому что у меня, например, глобально стоят другие
2. чтобы случайно не коммитнуть пропертис профиля дев, который для локального использования

2020-09-29 17:30 UTC, closed without merging

2020-10-05 14:05 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +
убраны
https://github.com/microservices-course-itmo/user-service/blob/sprint02/src/main/java/com/wine/to/up/user/service/controller/UserController.java#L15

2020-10-05 14:06 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/controller/UserController.java
> +    @GetMapping("/get")
пофикшено
https://github.com/microservices-course-itmo/user-service/blob/7c24259ba6868d6deda2dd39f827d53ec323e6d3/src/main/java/com/wine/to/up/user/service/controller/UserController.java#L19-L25

2020-10-05 14:07 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/dto/AbstractDto.java
> +public interface AbstractDto<I> {
Ограничение для абстрактного сервиса, про него в соответствующем треде
https://github.com/microservices-course-itmo/user-service/blob/7c24259ba6868d6deda2dd39f827d53ec323e6d3/src/main/java/com/wine/to/up/user/service/domain/dto/AbstractDto.java#L3-L10

2020-10-05 14:07 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/dto/RoleDto.java
> +    private Boolean accessToCatalog;
Пофикшено https://github.com/microservices-course-itmo/user-service/blob/7c24259ba6868d6deda2dd39f827d53ec323e6d3/src/main/java/com/wine/to/up/user/service/domain/dto/RoleDto.java#L12-L15

2020-10-05 14:08 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +public abstract class AbstractService
Типичные круд операции для каждой сущности одинаковые, поэтому и был сделан класс, от которого можно унаследоваться, написать две строчки и получить круд

2020-10-05 14:08 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +@Transactional
Цитирую предыдущий комментарий.

> Типичные круд операции для каждой сущности одинаковые, поэтому и был сделан класс, от которого можно унаследоваться, написать две строчки и получить круд.

2020-10-05 14:09 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/impl/RoleService.java
> +public class RoleService extends AbstractService<Long, RoleDto, Role, RoleRepository> {
RoleService - сервисный класс для ролей

2020-10-05 14:10 UTC, Kot1que commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming.physical-strategy=com.wine.to.up.user.service.configuration.NamingStrategy
9 - для валидации схемы, что она нормально маппита на энтити
10 - может быть можно и не указывать, но я за явное указание
11 - убрано

2020-10-05 14:10 UTC, Kot1que commented on pom.xml
> +
Сделано в спринте2

2020-10-05 14:15 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +@Transactional
> Цитирую предыдущий комментарий.
> 
> > Типичные круд операции для каждой сущности одинаковые, поэтому и был сделан класс, от которого можно унаследоваться, написать две строчки и получить круд.

тут попрос про аннотацию

2020-10-05 14:21 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/entity/AbstractEntity.java
> +public interface AbstractEntity<I> {
Тоже для ограничения. См. AbstractService
https://github.com/microservices-course-itmo/user-service/blob/7c24259ba6868d6deda2dd39f827d53ec323e6d3/src/main/java/com/wine/to/up/user/service/domain/entity/AbstractEntity.java#L3-L10

2020-10-05 14:25 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@Data
@Data включает:

- Getter (ок)
- Setter (ок)
- RequiredArgsConstructor (ок)
- ToString (не ок, может быть цикл при двусторонней связи)
- EqualsAndHashCode (не ок, лишние поля захватывает)

Последние два явно переопределены с исключениями
https://github.com/microservices-course-itmo/user-service/blob/7c24259ba6868d6deda2dd39f827d53ec323e6d3/src/main/java/com/wine/to/up/user/service/domain/entity/User.java#L14-L22
И добавлен `NoArgsConstructor` чтоб хибернейт мог создать объектик.

2020-10-05 14:25 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +@Table(name = "dim_city")
пофикшено, все таблицы переименованы

2020-10-05 14:26 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/domain/entity/City.java
> +    @Column(name = "CityId")
пофикшено, всё переименовали в снейк

2020-10-05 14:26 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/repository/AbstractRepository.java
> +public interface AbstractRepository<E extends AbstractEntity<I>, I> extends CrudRepository<E, I> {
Да, действительно не нужно, убрано

2020-10-05 14:27 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/CommonService.java
> +public interface CommonService<I, M extends AbstractDto<I>, E extends AbstractEntity<I>> {
Убрано, т.к. только AbstractService реализует интерфейс и в нем нет смысла

2020-10-05 14:31 UTC, Kot1que commented on src/main/java/com/wine/to/up/user/service/service/impl/AbstractService.java
> +@Transactional
Нет проблем.
`@Transactional` говорит, что на класс надо навесить прокси(что делает Bean Post Processor, какой точно не вспомню), который будет перед выполнением метода начинать транзакцию, после выполнения метода заканчивать ее (и откатывать в случае ошибки).